SDE-FIC/Models/UnidadeCurricular.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SDE_FIC.Models
{
    [Serializable]
    public class UnidadeCurricular
    {
        public long IdUnidadeCurricular { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
        public int CargaHoraria { get; set; }

        public virtual Curso Curso { get; set; }

    }
}

SDE-FIC/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Drawing;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
        public class SistemaController : Controller
        {
            private DBConnect _db = new DBConnect();

            public ViewResult VerificarSessao()
            {
                if (Session["LogedUserNomeCompleto"] == null)
                {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
                else
                {
                    var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
                }
                return View();
            }

            //
            // GET: /Sistema/

            public ActionResult Index()
            {
                VerificarSessao();

                int hora = DateTime.Now.Hour;
                ViewBag.Data = DateTime.Now.Date.ToString("D");
                ViewBag.Saudacao = hora < 12 ? "Bom dia" : hora < 18 ? "Boa tarde" : "Boa Noite";

                //TURMA
                TurmaDAO turmasDAO = new TurmaDAO(ref _db);
                List<Turma> lTurma = new List<Turma>();
                FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);
                Funcionario _funcionario = new Funcionario();


                if (Session["LogedUserPerfil"].ToString() != "professor")
                {
                    lTurma = turmasDAO.All().ToList();

                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }
                else
                {
                    _funcionario.IdFuncionario = funcionarioDAO.LoadByNome(Session["LogedUserNomeCompleto"].ToString()).IdFuncionario;
                    lTurma = turmasDAO.LoadByFuncionario(ref _funcionario, true).ToList();


                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }

                //Usuario
                UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
                ViewBag.Usuario = _usuarioDAO.All().Count();


                return View();
            }


            public ActionResult BaixarCalendario2015()
            {
                Response.AddHeader("Content-Disposition", "attachment; filename=\"Calendario2015.xls\"");
                Response.WriteFile(Server.MapPath("~/Content/Download/Calendario2015.xls"));
                return View("Index");
            }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Controllers/UnidadeCurricularController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using PagedList;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
    public class UnidadeCurricularController : Controller
    {
        private DBConnect _db = new DBConnect();

        public ViewResult VerificarSessao()
        {
            if (Session["LogedUserNomeCompleto"] == null)
            {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
            }
            return View();
        }

        //
        // GET: /UnidadeCurricular/

        public ActionResult Index(int? pagina, string strCriterioCurso)
        {

            VerificarSessao();
            int tamanhoPagina = 15;
            int numeroPagina = pagina ?? 1;

            UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
            
            List<UnidadeCurricular> lUnidadeCurricular = new List<UnidadeCurricular>();
            if (strCriterioCurso == null)
            {
                lUnidadeCurricular = _unidadecurricularDAO.All().OrderBy(x => x.Curso.CursoNome.ToUpper()).ToList();
            }
            else
            {
                lUnidadeCurricular = _unidadecurricularDAO.All().Where(x => x.Curso.CursoNome.ToUpper().Contains(strCriterioCurso.ToUpper())).OrderBy(x => x.Curso.CursoNome.ToUpper()).ToList();
            }

            return View("~/Views/Sistema/UnidadeCurricular/Index.cshtml", lUnidadeCurricular.ToPagedList(numeroPagina, tamanhoPagina));
        }

        //
        // GET: /UnidadeCurricular/Details/5

        public ActionResult Details(int id = 0)
        {
            VerificarSessao();
            UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
            UnidadeCurricular _unidadecurricular = new UnidadeCurricular();

            _unidadecurricular = _unidadecurricularDAO.LoadById(id);

            if (_unidadecurricular == null)
            {
                return HttpNotFound();
            }
            return View("~/Views/Sistema/UnidadeCurricular/Details.cshtml", _unidadecurricular);
        }

        //
        // GET: /UnidadeCurricular/Create

        public ActionResult Create()
        {
            VerificarSessao();

            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome.ToUpper()), "idcurso" , "cursonome".ToUpper());

            return View("~/Views/Sistema/UnidadeCurricular/Create.cshtml");
        }

        //
        // POST: /UnidadeCurricular/Create

        [HttpPost]
        public ActionResult Create(UnidadeCurricular unidadecurricular)
            {
                CursoDAO _cursoDAO = new CursoDAO(ref _db);


                if (ModelState.IsValid)
                {
                    UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
                    _unidadecurricularDAO.Insert(unidadecurricular);

                    this.Success(string.Format("Unidade Curricular Cadastrada com sucesso!"), true);
                    return RedirectToAction("Index");
                }
                this.Danger(string.Format("Registro NÃO Cadastrado, tente novamente!"), true);
                ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome), "idcurso", "cursonome", unidadecurricular.Curso.IdCurso);
                return View("~/Views/Sistema/UnidadeCurricular/Create.cshtml", unidadecurricular);
            }

        //
        // GET: /UnidadeCurricular/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VerificarSessao();

            UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
            UnidadeCurricular _unidadecurricular = new UnidadeCurricular();

            CursoDAO _cursoDAO = new CursoDAO(ref _db);
            Curso _curso = new Curso();
            
            _unidadecurricular = _unidadecurricularDAO.LoadById(id);

            if (_unidadecurricular == null)
            {
                return HttpNotFound();
            }
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome), "idcurso", "cursonome", _unidadecurricular.Curso.IdCurso);
            return View("~/Views/Sistema/UnidadeCurricular/Edit.cshtml", _unidadecurricular);
        }

        //
        // POST: /UnidadeCurricular/Edit/5

        [HttpPost]
        public ActionResult Edit(UnidadeCurricular unidadecurricular)
        {
            CursoDAO _cursoDAO = new CursoDAO(ref _db);
            UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
            UnidadeCurricular _unidadecurricular = new UnidadeCurricular();

            if (ModelState.IsValid)
            {
                _unidadecurricularDAO.Update(unidadecurricular);
                this.Success(string.Format("Registro Alterado com sucesso!"), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("Registro NÃO Alterado, tente novamente!"), true);
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome), "idcurso", "cursonome", _unidadecurricular.Curso.IdCurso);
            return View("~/Views/Sistema/UnidadeCurricular/Edit.cshtml", _unidadecurricular);
        }


        // POST: /UnidadeCurricular/Delete/5
        public ActionResult Delete(int id = 0)
        {
            UnidadeCurricularDAO _unidadecurricularDAO = new UnidadeCurricularDAO(ref _db);
            UnidadeCurricular _unidadecurricular = new UnidadeCurricular();
            _unidadecurricular = _unidadecurricularDAO.LoadById(id);

            if (_unidadecurricular != null)
            {
                _unidadecurricularDAO.Delete(_unidadecurricular);
                this.Success(string.Format("Registro Excluído com sucesso!"), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("Registro NÃO Excluído, tente novamente!"), true);
            return RedirectToAction("Index");
        }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Views/Sistema/UnidadeCurricular/Create.cshtml
@model SDE_FIC.Models.UnidadeCurricular

@{
    ViewBag.Title = "Unidade Curricular";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}



<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}
        <small>Nova @{@ViewBag.Title}</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/UnidadeCurricular" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    <label>Unidade Curricular</label>
 
                    @Html.TextBoxFor(model => model.Descricao, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Descricao)
                </div>

                <div class="form-group">
                    <label>Sigla</label>

                    @Html.TextBoxFor(model => model.Sigla, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Sigla)
                </div>

                <div class="form-group">
                    <label>Carga Horária (h)</label>

                    @Html.TextBoxFor(model => model.CargaHoraria, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CargaHoraria)
                </div>

                <div class="form-group">
                    <label>Curso</label>

                    @Html.DropDownListFor(model => Model.Curso.IdCurso, ViewBag.curso_idcurso as SelectList, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Curso.IdCurso)
                </div>

                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/UnidadeCurricular/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>
    
</section>

SDE-FIC/Views/Sistema/UnidadeCurricular/Edit.cshtml
@model SDE_FIC.Models.UnidadeCurricular

@{
    ViewBag.Title = "Unidade Curricular";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}



<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}s
        <small>Nova @{@ViewBag.Title}</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/UnidadeCurricular" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdUnidadeCurricular)

                <div class="form-group">
                    <label>Unidade Curricular</label>

                    @Html.TextBoxFor(model => model.Descricao, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Descricao)
                </div>

                <div class="form-group">
                    <label>Sigla</label>

                    @Html.TextBoxFor(model => model.Sigla, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Sigla)
                </div>

                <div class="form-group">
                    <label>Carga Horária (h)</label>

                    @Html.TextBoxFor(model => model.CargaHoraria, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CargaHoraria)
                </div>

                <div class="form-group">
                    <label>Curso</label>

                    @Html.DropDownListFor(model => Model.Curso.IdCurso, ViewBag.curso_idcurso as SelectList, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Curso.IdCurso)
                </div>

                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/UnidadeCurricular/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>

</section>

SDE-FIC/Views/Sistema/UnidadeCurricular/Index.cshtml
@model PagedList.IPagedList<SDE_FIC.Models.UnidadeCurricular>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Unidade Curricular";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}
        <small>Lista de Unidades Curriculares cadastradas</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <!---INICIO CONTEUDO-->
                <!---TOPO -->
                <div class="box-header no-padding">
                    <div class="box box-success collapsed-box">
                        <div class="box-header with-border">
                            <div class="row">
                                <div class="col-sm-4">
                                    <a href="~/UnidadeCurricular/Create" class="btn btn-success"><i class="fa fa-plus-circle"></i>&nbsp;Nova Unidade Curricular</a>
                                </div>
                                <!--Buscar Aluno-->
                                <div class="col-sm-5">
                                    @using (Html.BeginForm())
                                    {
                                        <div class="input-group input-group-sm">
                                            @Html.TextBox("strCriterioCurso", null, new { @class = "form-control pull-right", @style = "height: 35px;", @placeholder = "Curso..." })
                                            <span class="input-group-btn">
                                                <button type="submit" class="btn btn-info btn-flat" style="height: 35px;"><i class="fa fa-search"></i></button>
                                            </span>
                                        </div>
                                    }

                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <!---FIM TOPO -->
                <!---INICIO DATATABLE -->
                @if (Model != null)
                {
                    <div class="box-body table-responsive">

                        <table class="table table-hover dataTable dataTables_sizing">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>
                                        Nome do Curso
                                    </th>
                                    <th>
                                        Unidade Curricular
                                    </th>
                                    <th>
                                        Sigla
                                    </th>
                                    <th>
                                        Carga Horária (h)
                                    </th>
                                    <th style="text-align:center;">Ação</th>
                                </tr>

                            </thead>
                            @{ int i = Model.FirstItemOnPage - 1;
                               string Teste = "Curso";

                                foreach (var item in Model.OrderBy(x => x.Curso.CursoNome))
                                {

                            <tr>
                                <td>
                                    @if (item.Curso.CursoNome == Teste)
                                    {
                                        <br />
                                    }
                                    else
                                    {
                                        Write((i = (i + 1)) + ".");                                        
                                    }           
                                    
                                </td>
                                <td>

                                    @if (item.Curso.CursoNome == Teste)
                                    {
                                        <br />
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => item.Curso.CursoNome)
                                    }
                                    @{Teste = item.Curso.CursoNome;}

                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descricao)
                                </td>
                                <td style="text-align:center;">
                                    @item.Sigla.ToUpper()

                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(modelItem => item.CargaHoraria)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "UnidadeCurricular", new { id = item.IdUnidadeCurricular })"><img src="~/Content/img/editar.png" alt="Editar" /></a>
                                    <a href="#" type="button" data-toggle="modal" data-target="#modal_danger_@item.IdUnidadeCurricular"><img src="~/Content/img/excluir.png" alt="Excluir" /></a>

                                    <!--MODAL PARA EXCLUSÃO-->

                                    <div class="modal modal-danger fade in"id="modal_danger_@item.IdUnidadeCurricular" style="display: none; padding-right: 17px;">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Cuidado</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>

                                                </div>
                                                <div class="modal-body">

                                                    <p>Tem certeza de que deseja excluir a Unidade Curricular cadastrada?</p>
                                                    <p>Nome: @item.Descricao</p>
                                                    <p>Carga Horária: @item.CargaHoraria h</p>


                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancelar</button>
                                                    <!--<button type="button" class="btn btn-outline">Sim</button>-->
                                                    <a href="@Url.Action("Delete", "UnidadeCurricular", new { id = item.IdUnidadeCurricular })" class="btn btn-outline">Sim</a>
                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>


                                </td>
                            </tr>

                                }
                            }

                        </table>

                        <div class="box-footer clearfix">
                            <div class="row">Listando de @Model.FirstItemOnPage a @Model.LastItemOnPage de um total de @Model.TotalItemCount</div>
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { pagina = page, strCriterio = ViewBag.strCriterio }))
                        </div>
                    </div>
                }
                <!---Fim DATATABLE -->
                <!--FIM CONTEUDO-->
            </div>
        </div>
    </div>
</section>