SDE-FIC/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDE_FIC.Models
{
    [Serializable]
    public class Funcionario
    {
        //public Funcionario()
        //{
        //    this.Turmas = new HashSet<Turma>();
        //}

        [Required(ErrorMessage = "Defina o nome do Professor")]
        public int IdFuncionario { get; set; }

        //[Required(ErrorMessage = "Informe um Nome para o Funcionário")]
        public string NomeCompleto { get; set; }
        public string Email { get; set; }
        public string TelefoneCelular { get; set; }
        public string TelefoneResidencial { get; set; }
        public string Especialidade { get; set; }
        public string Observacao { get; set; }

        [Required(ErrorMessage = "Informe um usuário para o Funcionário")]
        public int IdUsuario { get; set; }       
        //Chave Estrangeira
        public virtual Usuario Usuario { get; set; }

        public virtual ICollection<Turma> Turmas { get; set; }

    }
}

SDE-FIC/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
//using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using PagedList;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
    public class FuncionarioController : Controller
    {
        private DBConnect _db = new DBConnect();


        public ViewResult VerificarSessao()
        {
            if (Session["LogedUserNomeCompleto"] == null)
            {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
            }
            return View();
        }


        //
        // GET: /Funcionario/
        public ActionResult Index(int? pagina, string strCriterio)
        {
            VerificarSessao();

            int tamanhoPagina = 15;
            int numeroPagina = pagina ?? 1;

            FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);

            List<Funcionario> lFuncionario = new List<Funcionario>();

            ViewBag.listarFuncionario = lFuncionario;

            if (strCriterio == null)
            {
                lFuncionario = funcionarioDAO.All().OrderBy(x => x.NomeCompleto.ToUpper()).ToList();
            }
            else
            {
                lFuncionario = funcionarioDAO.All().Where(x => x.NomeCompleto.ToUpper().Contains(strCriterio.ToUpper())).OrderBy(x => x.NomeCompleto.ToUpper()).ToList();
                ViewBag.strCriterio = strCriterio.ToString();
            }

            return View("~/Views/Sistema/Funcionario/Index.cshtml", lFuncionario.ToPagedList(numeroPagina, tamanhoPagina));
        }

        //
        // GET: /Professor/Details/5

        public ActionResult Details(int id = 0)
        {
            VerificarSessao();

            FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);
            Funcionario _funcionario = new Funcionario();
            _funcionario = funcionarioDAO.LoadById(id);
            if (_funcionario == null)
            {
                return HttpNotFound();
            }
            return View("~/Views/Sistema/Funcionario/Details.cshtml", _funcionario);
        }

        //
        // GET: /Funcionario/Create

        public ActionResult Create()
        {
            VerificarSessao();

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username");

            return View("~/Views/Sistema/Funcionario/Create.cshtml");
        }

        //
        // POST: /Funcionario/Create

        [HttpPost]
        public ActionResult Create(Funcionario funcionario)
        {
            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);

            if (ModelState.IsValid)
            {               
                FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);
                _funcionarioDAO.Insert(funcionario);
                this.Success(string.Format("Registro salvo com sucesso!"), true);
                return RedirectToAction("Index");
            }
            else {
                ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username");
                this.Danger(string.Format("Falha ao Cadastrar Registro! Verifique se os campos estão preenchidos."));
                return View("~/Views/Sistema/Funcionario/Create.cshtml");
            }

            
        }

        //
        // GET: /Funcionario/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VerificarSessao();

            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);
            Funcionario _funcionario = new Funcionario();

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db); 
            Usuario _usuario = new Usuario();

            _funcionario = _funcionarioDAO.LoadById(id);

            if (_funcionario == null)
            {
                return HttpNotFound();
            }
            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username", _funcionario.Usuario.IdUsuario);
            return View("~/Views/Sistema/Funcionario/Edit.cshtml", _funcionario);
        }

        //
        // POST: /Funcionario/Edit/5
        [HttpPost]
        public ActionResult Edit(Funcionario funcionario)
        {
            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);
            Funcionario _funcionario = new Funcionario();

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = new Usuario();

            if (ModelState.IsValid)
            {
                _funcionarioDAO.Update(funcionario);
                this.Success(string.Format("Registro salvo com sucesso!"), true);
                return RedirectToAction("Index");
            }

            //ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username", _funcionario.Usuario.IdUsuario);
            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username");
            this.Danger(string.Format("Falha ao Cadastrar Registros! Verifique se os campos estão preenchidos."));
            return View("~/Views/Sistema/Funcionario/Edit.cshtml", _funcionario);
        }

       //
        // POST: /Funcionario/Delete/5
        public ActionResult Delete(int id = 0)
        {
            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);
            Funcionario _funcionario = _funcionarioDAO.LoadById(id);
           
            if (_funcionario != null)
            {
                _funcionarioDAO.Delete(_funcionario.IdFuncionario);
                this.Success(string.Format("Registro EXCLUÍDO com sucesso!"), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("Falha ao Excluir Registros!"));
            return RedirectToAction("Index");
        }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Drawing;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
        public class SistemaController : Controller
        {
            private DBConnect _db = new DBConnect();

            public ViewResult VerificarSessao()
            {
                if (Session["LogedUserNomeCompleto"] == null)
                {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
                else
                {
                    var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
                }
                return View();
            }

            //
            // GET: /Sistema/

            public ActionResult Index()
            {
                VerificarSessao();

                int hora = DateTime.Now.Hour;
                ViewBag.Data = DateTime.Now.Date.ToString("D");
                ViewBag.Saudacao = hora < 12 ? "Bom dia" : hora < 18 ? "Boa tarde" : "Boa Noite";

                //TURMA
                TurmaDAO turmasDAO = new TurmaDAO(ref _db);
                List<Turma> lTurma = new List<Turma>();
                FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);
                Funcionario _funcionario = new Funcionario();


                if (Session["LogedUserPerfil"].ToString() != "professor")
                {
                    lTurma = turmasDAO.All().ToList();

                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }
                else
                {
                    _funcionario.IdFuncionario = funcionarioDAO.LoadByNome(Session["LogedUserNomeCompleto"].ToString()).IdFuncionario;
                    lTurma = turmasDAO.LoadByFuncionario(ref _funcionario, true).ToList();


                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }

                //Usuario
                UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
                ViewBag.Usuario = _usuarioDAO.All().Count();


                return View();
            }


            public ActionResult BaixarCalendario2015()
            {
                Response.AddHeader("Content-Disposition", "attachment; filename=\"Calendario2015.xls\"");
                Response.WriteFile(Server.MapPath("~/Content/Download/Calendario2015.xls"));
                return View("Index");
            }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Views/Sistema/Funcionario/Create.cshtml
@model SDE_FIC.Models.Funcionario

@{
    ViewBag.Title = "Funcionário";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}s
        <small>Editar Funcionário</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/Funcionario" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label>Nome Completo</label>

                    @Html.TextBoxFor(model => model.NomeCompleto, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NomeCompleto)
                </div>

                <div class="form-group">
                    <label>E-mail</label>

                    @Html.TextBoxFor(model => model.Email, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
                <div class="form-group">
                    <label>Celular</label>

                    @Html.TextBoxFor(model => model.TelefoneCelular, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TelefoneCelular)
                </div>

                <div class="form-group">
                    <label>Telefone Residencial</label>

                    @Html.TextBoxFor(model => model.TelefoneResidencial, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TelefoneResidencial)
                </div>

                <div class="form-group">
                    <label>Associar Usuário</label>

                    @Html.DropDownListFor(model => Model.IdUsuario, ViewBag.usuario_idusuario as SelectList, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdUsuario)
                </div>

                <div class="form-group">
                    <label>Especialidade</label>

                    @Html.TextBoxFor(model => model.Especialidade, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Especialidade)
                </div>

                <div class="form-group">
                    <label>Observação</label>

                    @Html.TextAreaFor(model => model.Observacao, new { @class = "form-control", @Rows = "4" })
                    @Html.ValidationMessageFor(model => model.Observacao)
                </div>

                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/Usuario/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>

    </div>

</section>

SDE-FIC/Views/Sistema/Funcionario/Edit.cshtml
@model SDE_FIC.Models.Funcionario

@{
    ViewBag.Title = "Funcionário";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}s
        <small>Editar Funcionário</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/Funcionario" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(Model => Model.IdFuncionario)

                <div class="form-group">
                    <label>Nome Completo</label>

                    @Html.TextBoxFor(model => model.NomeCompleto, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NomeCompleto)
                </div>

                <div class="form-group">
                    <label>E-mail</label>

                    @Html.TextBoxFor(model => model.Email, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
                <div class="form-group">
                    <label>Celular</label>

                    @Html.TextBoxFor(model => model.TelefoneCelular, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TelefoneCelular)
                </div>

                <div class="form-group">
                    <label>Telefone Residencial</label>

                    @Html.TextBoxFor(model => model.TelefoneResidencial, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TelefoneResidencial)
                </div>

                <div class="form-group">
                    <label>Associar Usuário</label>

                    @Html.DropDownListFor(model => Model.IdUsuario, ViewBag.usuario_idusuario as SelectList, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdUsuario)
                </div>

                <div class="form-group">
                    <label>Especialidade</label>

                    @Html.TextBoxFor(model => model.Especialidade, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Especialidade)
                </div>

                <div class="form-group">
                    <label>Observação</label>

                    @Html.TextAreaFor(model => model.Observacao, new { @class = "form-control", @Rows = "4" })
                    @Html.ValidationMessageFor(model => model.Observacao)
                </div>

                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/Usuario/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>

    </div>

</section>

SDE-FIC/Views/Sistema/Funcionario/Index.cshtml
@model PagedList.IPagedList<SDE_FIC.Models.Funcionario>
@using PagedList.Mvc

@{
    ViewBag.Title = "Funcionário";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";

}
<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}s
        <small>Lista de funcinário cadastrados</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <!---INICIO CONTEUDO-->
                <!---TOPO -->
                <div class="box-header no-padding">
                    <div class="box box-success collapsed-box">
                        <div class="box-header with-border">
                            <div class="row">
                                <div class="col-sm-3">
                                    <a href="~/Funcionario/Create" class="btn btn-success"><i class="fa fa-plus-circle"></i>&nbsp;Novo Funcionário</a>
                                </div>
                                <!--Buscar Aluno-->
                                <div class="col-sm-5">
                                    @using (Html.BeginForm())
                                    {
                                        <div class="input-group input-group-sm" style="width: 250px;">
                                            @Html.TextBox("strCriterio", null, new { @class = "form-control", @style = "height: 35px;", @placeholder = "Funcionário..." })
                                            <span class="input-group-btn">
                                                <button type="submit" class="btn btn-info btn-flat" style="height: 35px;"><i class="fa fa-search"></i></button>
                                            </span>
                                        </div>
                                    }

                                </div>
                            </div>
                           
                        </div>
                    </div>
                </div>
                <!---FIM TOPO -->
                <!---INICIO DATATABLE -->
                @if (Model != null)
                {
                    <div class="box-body table-responsive">

                        <table class="table table-hover dataTable dataTables_sizing">
                            <thead>
                                <tr>
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>
                                        Nome Completo
                                    </th>
                                    <th>
                                        Perfil
                                    </th>
                                    <th>
                                        Usuário
                                    </th>
                                    <th>
                                        E-mail
                                    </th>
                                    <th style="text-align:center;">Ação</th>
                                </tr>

                            </thead>
                            @{ int i = Model.FirstItemOnPage - 1;

                                foreach (var item in Model.OrderBy(x => x.NomeCompleto))
                                {

                                    <tr>
                                        <td>@(i = (i + 1)).</td>
                                        <td>
                                            @item.NomeCompleto.ToUpper()
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Usuario.Perfil)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Usuario.Username)
                                        </td>
                                        <td>
                                            @item.Email.ToLower()
                                        </td>
                                        <td style="text-align:center; width: 100px;">
                                            <a href="@Url.Action("Edit", "Funcionario", new { id = item.IdFuncionario })"><img src="~/Content/img/editar.png" alt="Editar" /></a>
                                            <a href="#" type="button" data-toggle="modal" data-target="#modal_danger_@item.IdFuncionario"><img src="~/Content/img/excluir.png" alt="Excluir" /></a>

                                            <!--MODAL PARA EXCLUSÃO-->
                                            <div class="modal modal-danger fade" id="modal_danger_@item.IdFuncionario" style="display: none;">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">×</span>
                                                            </button>
                                                            <h4 class="modal-title">Cuidado</h4>
                                                        </div>
                                                        <div class="modal-body">

                                                            <p>Tem certeza de que deseja excluir o funcionário cadastrado?</p>
                                                            <p>Nome: @item.NomeCompleto</p>
                                                            <p>E-mail: @item.Email</p>
                                                            

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancelar</button>
                                                            <!--<button type="button" class="btn btn-outline">Sim</button>-->
                                                            <a href="@Url.Action("Delete", "Funcionario", new { id = item.IdFuncionario })" class="btn btn-outline">Sim</a>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>


                                        </td>
                                    </tr>

                                }
                            }

                        </table>

                        <div class="box-footer clearfix">
                            <div class="row">Listando de @Model.FirstItemOnPage a @Model.LastItemOnPage de um total de @Model.TotalItemCount</div>
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { pagina = page, strCriterio = ViewBag.strCriterio }))
                        </div>
                    </div>
                }
                <!---Fim DATATABLE -->
                <!--FIM CONTEUDO-->
            </div>
        </div>
    </div>
</section>