SDE-FIC/Models/Sugestoes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDE_FIC.Models
{
    [Serializable]
    public class Sugestoes
    {
        public int IdSugestao { get; set; }
        public string Tipo { get; set; }
        [Required(ErrorMessage = "Informe um Titulo para a Sugestão")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "Informe uma Descrição para a Sugestão")]
        public string Descricao { get; set; }
        public string Status { get; set; }

        [Required(ErrorMessage = "Informe um usuário para o Funcionário")]
        public int IdUsuario { get; set; }
        //Chave Estrangeira
        public virtual Usuario Usuario { get; set; }

    }
}

SDE-FIC/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Drawing;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
        public class SistemaController : Controller
        {
            private DBConnect _db = new DBConnect();

            public ViewResult VerificarSessao()
            {
                if (Session["LogedUserNomeCompleto"] == null)
                {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
                else
                {
                    var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
                }
                return View();
            }

            //
            // GET: /Sistema/

            public ActionResult Index()
            {
                VerificarSessao();

                int hora = DateTime.Now.Hour;
                ViewBag.Data = DateTime.Now.Date.ToString("D");
                ViewBag.Saudacao = hora < 12 ? "Bom dia" : hora < 18 ? "Boa tarde" : "Boa Noite";

                //TURMA
                TurmaDAO turmasDAO = new TurmaDAO(ref _db);
                List<Turma> lTurma = new List<Turma>();
                FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);
                Funcionario _funcionario = new Funcionario();


                if (Session["LogedUserPerfil"].ToString() != "professor")
                {
                    lTurma = turmasDAO.All().ToList();

                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }
                else
                {
                    _funcionario.IdFuncionario = funcionarioDAO.LoadByNome(Session["LogedUserNomeCompleto"].ToString()).IdFuncionario;
                    lTurma = turmasDAO.LoadByFuncionario(ref _funcionario, true).ToList();


                    //Diario
                    ViewBag.Turma = lTurma.Count();
                    ViewBag.DiariosAtivo = lTurma.Where(x => x.Status == true).Count();
                    ViewBag.DiariosFinalizado = lTurma.Where(x => x.Status == false).Count();
                }

                //Usuario
                UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
                ViewBag.Usuario = _usuarioDAO.All().Count();


                return View();
            }


            public ActionResult BaixarCalendario2015()
            {
                Response.AddHeader("Content-Disposition", "attachment; filename=\"Calendario2015.xls\"");
                Response.WriteFile(Server.MapPath("~/Content/Download/Calendario2015.xls"));
                return View("Index");
            }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Controllers/SugestoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using PagedList;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
    public class SugestoesController : Controller
    {
        private DBConnect _db = new DBConnect();

        public ViewResult VerificarSessao()
        {
            if (Session["LogedUserNomeCompleto"] == null)
            {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
            }
            return View();
        }


        //
        // GET: /UnidadeCurricular/

        public ActionResult Index(int? pagina)
        {
            VerificarSessao();

            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;
            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            SugestoesDAO _sugestoesDAO = new SugestoesDAO(ref _db);

            return View("~/Views/Sistema/Sugestoes/Index.cshtml", _sugestoesDAO.All().ToPagedList(numeroPagina, tamanhoPagina));
        }

 
        //
        // GET: /UnidadeCurricular/Create

        public ActionResult Create(int id = 0)
        {
            VerificarSessao();

            id = Convert.ToInt32(Session["LogedUserId"].ToString());

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario usuario = new Usuario();
            usuario = _usuarioDAO.LoadById(id);

            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username");

            Sugestoes sugestoes = new Sugestoes();
            sugestoes.Usuario = usuario;

            return View("~/Views/Sistema/Sugestoes/Create.cshtml", sugestoes);
        }

        //
        // POST: /UnidadeCurricular/Create

        [HttpPost]
        public ActionResult Create(Sugestoes sugestoes)
            {
                SugestoesDAO _sugestoesDAO = new SugestoesDAO(ref _db);
                UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
                sugestoes.Usuario = _usuarioDAO.LoadById(sugestoes.IdUsuario);

                if (ModelState.IsValid)
                {
                    _sugestoesDAO.Insert(sugestoes);

                    this.Success(string.Format("Sugestão Cadastrada com sucesso!"), true);
                    return RedirectToAction("Index");
                }
    
                this.Danger(string.Format("Erro ao cadastrar, tente novamente!"), true);
                ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username");
                return View("~/Views/Sistema/Sugestoes/Create.cshtml", sugestoes);
            }

        //
        // GET: /UnidadeCurricular/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VerificarSessao();

            SugestoesDAO _sugestoesDAO = new SugestoesDAO(ref _db);
            Sugestoes _sugestoes = new Sugestoes();

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = new Usuario();
            
            _sugestoes = _sugestoesDAO.LoadById(id);

            if (_sugestoes == null)
            {
                return HttpNotFound();
            }
            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username", _sugestoes.Usuario.IdUsuario);
            return View("~/Views/Sistema/Sugestoes/Edit.cshtml", _sugestoes);
        }

        //
        // POST: /UnidadeCurricular/Edit/5

        [HttpPost]
        public ActionResult Edit(Sugestoes sugestoes)
        {
            SugestoesDAO _sugestoesDAO = new SugestoesDAO(ref _db);
            Sugestoes _sugestoes = new Sugestoes();
            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = new Usuario();

            if (ModelState.IsValid)
            {
                _sugestoesDAO.Update(sugestoes);
                this.Success(string.Format("Registro Alterado com sucesso!"), true);
                return RedirectToAction("Index");
            }
            TempData["Erro"] = "1";
            this.Success(string.Format("Sugestão não alterada, tente novamente!"), true);
            ViewBag.usuario_idusuario = new SelectList(_usuarioDAO.All().ToList(), "idusuario", "username", sugestoes.Usuario.IdUsuario);
            return View("~/Views/Sistema/Sugestoes/Edit.cshtml", _sugestoes);
        }



        public ActionResult Delete(Sugestoes sugestoes)
        {
            SugestoesDAO _sugestoesDAO = new SugestoesDAO(ref _db);
            Sugestoes _sugestoes = new Sugestoes();
            _sugestoes = _sugestoesDAO.LoadById(sugestoes.IdSugestao);

            if (_sugestoes != null)
            {
                _sugestoesDAO.Delete(sugestoes.IdSugestao);

                this.Success(string.Format("Registro Excluído com sucesso!"), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("Erro ao Excluir, tente novamente!"), true);
            return View("~/Views/Sistema/Sugestoes/Delete.cshtml", sugestoes);
        }

        //    protected override void Dispose(bool disposing)
        //    {
        //        db.Dispose();
        //        base.Dispose(disposing);
        //    }
        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Views/Sistema/Sugestoes/Create.cshtml
@model SDE_FIC.Models.Sugestoes
@{
    ViewBag.Title = "Sugestões";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}
        <small>Nova @{@ViewBag.Title}</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/Sugestoes" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">
                <div class="form-group col-md-2">
                    <label>Tipo</label>
                    @Html.DropDownListFor(model => model.Tipo, new SelectList(
                          new List<Object>{
                                            new { value =  "Correção" , text =  "Correção"  },
                                            new { value =  "Nova Função" , text =  "Nova Função"  },
                                            new { value =  "Erro" , text =  "Erro"  },
                                          },"value","text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Tipo)
                </div>
                <div class="form-group col-md-6">
                    <label>Titulo/Local</label>
                    @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Titulo)
                </div>

                @Html.HiddenFor(model => Model.IdUsuario, new { Value = Model.Usuario.IdUsuario, @class = "form-control" })

                <div class="form-group col-md-2">
                    <label>Status</label>
                    @Html.DropDownListFor(model => model.Status, new SelectList(
                                 new List<Object>{
                                                   new { value =  "Aberto" , text =  "Aberto"  },
                                                   new { value =  "Iniciado" , text =  "Iniciado"  },
                                                   new { value =  "Finalizado" , text =  "Finalizado"  },
                                                 },"value","text"), new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.Status)
                </div>

            </div>
            <div class="row">
                <div class="form-group col-md-10">
                    <label>Descrição</label>
                    @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Descricao)
                </div>
            </div>

                <div class="box-footer col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/Sugestoes/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>

</section>

SDE-FIC/Views/Sistema/Sugestoes/Edit.cshtml
@model SDE_FIC.Models.Sugestoes
@{
    ViewBag.Title = "Sugestões";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}
        <small>Nova @{@ViewBag.Title}</small>
    </h1>
</section>
<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="~/Sugestoes" class="link-black"><i class="fa fa-close"></i></a>
            </div>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdSugestao)

                <div class="row">
                    <div class="form-group col-md-2">
                        <label>Tipo</label>
                        @Html.DropDownListFor(model => model.Tipo, new SelectList(
                              new List<Object>{
                                                new { value =  "Correção" , text =  "Correção"  },
                                                new { value =  "Nova Função" , text =  "Nova Função"  },
                                                new { value =  "Erro" , text =  "Erro"  },
                                              },"value","text"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Tipo)
                    </div>
                    <div class="form-group col-md-6">
                        <label>Titulo/Local</label>
                        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Titulo)
                    </div>

                    @Html.HiddenFor(model => Model.IdUsuario, new { Value = Model.Usuario.IdUsuario, @class = "form-control" })

                    <div class="form-group col-md-2">
                        <label>Status</label>
                        @Html.DropDownListFor(model => model.Status, new SelectList(
                                     new List<Object>{
                                                       new { value =  "Aberto" , text =  "Aberto"  },
                                                       new { value =  "Iniciado" , text =  "Iniciado"  },
                                                       new { value =  "Finalizado" , text =  "Finalizado"  },
                                                     },"value","text"), new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.Status)
                    </div>

                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                        <label>Descrição</label>
                        @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Descricao)
                    </div>
                </div>

                <div class="box-footer col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-success" id="btnSubmit" />
                    <a href="/Sugestoes/Create" class="btn btn-default pull-right">Limpar</a>
                </div>

            }

        </div>

    </div>

</section>

SDE-FIC/Views/Sistema/Sugestoes/Index.cshtml
@model PagedList.IPagedList<SDE_FIC.Models.Sugestoes>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Sugestões";
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<section class="content-header">
    <h1>
        Cadastro de @{@ViewBag.Title}
        <small>Lista de Sugestões realizadas</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <!---INICIO CONTEUDO-->
                <!---TOPO -->
                <div class="box-header no-padding">
                    <div class="box box-success collapsed-box">
                        <div class="box-header with-border">
                            <div class="col-sm-3">
                                <a href="~/Sugestoes/Create" class="btn btn-success"><i class="fa fa-plus-circle"></i>&nbsp;Nova Sugestão</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!---FIM TOPO -->
                <!---INICIO DATATABLE -->
                @if (Model != null)
                {
                    <div class="box-body table-responsive">

                        <table class="table table-hover dataTable dataTables_sizing">
                            <thead>
                                <tr>
                                    <th>
                                        Tipo
                                    </th>
                                    <th>
                                        Titulo
                                    </th>
                                    <th>
                                        Descrição
                                    </th>
                                    <th style="text-align:center;">
                                        Usuário
                                    </th>
                                    <th style="text-align:center;">
                                        Status
                                    </th>
                                    @if (Session["LogedUserPerfil"].ToString() == "coordenador")
                                    {
                                        <th style="text-align:center;">Ação</th>
                                    }
                                   </tr>

                            </thead>
                            @foreach (var item in Model.OrderBy(x => x.Status))
                                {

                            <tr>
                                <td >
                                    <small>
                                        @Html.DisplayFor(modelItem => item.Tipo)
                                    </small>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Titulo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descricao)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(modelItem => item.Usuario.Username)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>

                                @if (Session["LogedUserPerfil"].ToString() == "coordenador")
                                {
                                <td style="text-align:center; width: 100px;">
                                    <a href="@Url.Action("Edit", "Sugestoes", new { id = item.IdSugestao })"><img src="~/Content/img/editar.png" alt="Editar" /></a>                                    
                                    <a href="#" type="button" data-toggle="modal" data-target="#modal_danger_@item.IdSugestao"><img src="~/Content/img/excluir.png" alt="Excluir" /></a>

                                    <!--MODAL PARA EXCLUSÃO-->
                                    <div class="modal modal-danger fade" id="modal_danger_@item.IdSugestao" style="display: none;">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                    <h4 class="modal-title">Cuidado</h4>
                                                </div>
                                                <div class="modal-body">

                                                    <p>Tem certeza de que deseja excluir a Sugestão cadastrada?</p>
                                                    <p>Titulo: @item.Titulo</p>
                                                    <p>Descrição: @item.Descricao</p>
                                                    


                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancelar</button>
                                                    <!--<button type="button" class="btn btn-outline">Sim</button>-->
                                                    <a href="@Url.Action("Delete", "Sugestoes", new { id = item.IdSugestao })" class="btn btn-outline">Sim</a>
                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>
                                </td>
                                }
                                            
                            </tr>


                                
                            }

                        </table>

                        <div class="box-footer clearfix">
                            <div class="row">Listando de @Model.FirstItemOnPage a @Model.LastItemOnPage de um total de @Model.TotalItemCount</div>
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { pagina = page, strCriterio = ViewBag.strCriterio }))
                        </div>
                    </div>
                }
                <!---Fim DATATABLE -->
                <!--FIM CONTEUDO-->
            </div>
        </div>
    </div>
</section>