SDE-FIC/Controllers/TurmaController.cs
using SDE_FIC.DAO;
using SDE_FIC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
{
    public class TurmaController : Controller
    {
        private DBConnect _db = new DBConnect();

        public ViewResult VerificarSessao()
        {
            if (Session["LogedUserNomeCompleto"] == null)
            {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
            }
            return View();
        }


        //
        // GET: /Turma/

        public ActionResult Index(int? pagina, string strCriterioTurma, string strCriterioProfessor, string strCriterioCurso, int strCriterioStatus = 1)
        {
            VerificarSessao();

            int tamanhoPagina = 15;
            int numeroPagina = pagina ?? 1;

            CursoDAO _cursoDAO = new CursoDAO(ref _db);
            
            TurmaDAO turmasDAO = new TurmaDAO(ref _db);            
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO(ref _db);
            Funcionario _funcionario = new Funcionario();

            List<Turma> lTurma = new List<Turma>();

            ViewBag.strCriterioTurma = strCriterioTurma;
            ViewBag.strCriterioCurso = strCriterioCurso;
            ViewBag.strCriterioProfessor = strCriterioProfessor;

            if (Session["LogedUserPerfil"].ToString() != "professor")
            {

                lTurma = turmasDAO.All().OrderByDescending(x => x.Idturma).ToList();

                if (strCriterioStatus == 1)
                {
                    lTurma = lTurma.Where(x => x.Status == true).ToList();
                }
                else if (strCriterioStatus == 0)
                {
                    lTurma = lTurma.Where(x => x.Status == false).ToList();
                }

                if (strCriterioProfessor != null)
                    lTurma = lTurma.Where(x => x.Funcionario.NomeCompleto.ToUpper().Contains(strCriterioProfessor.ToUpper())).ToList();

                if (strCriterioCurso != null)
                    lTurma = lTurma.Where(x => x.Curso.CursoNome.ToUpper().Contains(strCriterioCurso.ToUpper())).ToList();

                if (strCriterioTurma != null)
                    lTurma = lTurma.Where(x => x.Descricao.ToUpper().Contains(strCriterioTurma.ToUpper())).ToList();

                return View("~/Views/Sistema/Turma/Index.cshtml", lTurma.ToPagedList(numeroPagina, tamanhoPagina));
            }
            else 
            {
                var NomeCompleto = Session["LogedUserNomeCompleto"].ToString();
                _funcionario.IdFuncionario = funcionarioDAO.LoadByNome(NomeCompleto).IdFuncionario;

                lTurma = turmasDAO.LoadByFuncionario(ref _funcionario, true).OrderByDescending(x => x.Idturma).ToList();

                //lTurma = turmasDAO.All().OrderByDescending(x => x.Idturma).ToList();

                if (strCriterioStatus == 1)
                {
                    lTurma = lTurma.Where(x => x.Status == true).ToList();
                }
                else if (strCriterioStatus == 0)
                {
                    lTurma = lTurma.Where(x => x.Status == false).ToList();
                }

                if (strCriterioProfessor != null)
                    lTurma = lTurma.Where(x => x.Funcionario.NomeCompleto.ToUpper().Contains(strCriterioProfessor.ToUpper())).ToList();

                if (strCriterioCurso != null)
                    lTurma = lTurma.Where(x => x.Curso.CursoNome.ToUpper().Contains(strCriterioCurso.ToUpper())).ToList();

                if (strCriterioTurma != null)
                    lTurma = lTurma.Where(x => x.Descricao.ToUpper().Contains(strCriterioTurma.ToUpper())).ToList();


                if (lTurma == null)
                {
                    return View("~/Views/Sistema/Turma/Index.cshtml");
                }
                else {
                    return View("~/Views/Sistema/Turma/Index.cshtml", lTurma.OrderBy(x => x.Descricao).ToPagedList(numeroPagina, tamanhoPagina));
                }
                
            }

        }

        //
        // GET: /Turma/Details/5

        public ActionResult Details(int Id = 0)
        {
            VerificarSessao();
            TurmaDAO turmasDAO = new TurmaDAO(ref _db);
            Turma _turma = new Turma();
            _turma = turmasDAO.LoadById(Id);

            if (_turma == null)
            {
                return HttpNotFound();
            }
            return View("~/Views/Sistema/Turma/Details.cshtml", _turma);
        }

        //
        // GET: /Turma/Create

        public ActionResult Create()
        {
            VerificarSessao();

            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);

            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().OrderBy(x => x.CursoNome.ToUpper()), "idcurso", "cursonome");
            ViewBag.funcionario_idfuncionario = new SelectList(_funcionarioDAO.All().Where(x => x.Usuario.Perfil == "professor").OrderBy(x => x.NomeCompleto.ToUpper()), "idfuncionario", "nomecompleto");
            return View("~/Views/Sistema/Turma/Create.cshtml");

        }

        //
        // POST: /Turma/Create

        [HttpPost]
        public ActionResult Create(Turma turma)
        {
            CursoDAO _cursoDAO = new CursoDAO(ref _db);
            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);
            turma.Curso = _cursoDAO.LoadById(turma.Curso.IdCurso);
            turma.Funcionario = _funcionarioDAO.LoadById(turma.Funcionario.IdFuncionario);
            if (turma.Funcionario != null)
            {
                string NomeCompletoFuncionario = turma.Funcionario.NomeCompleto;
                turma.Funcionario.NomeCompleto = NomeCompletoFuncionario;
            }

            if (ModelState.IsValid)
            {
                TurmaDAO _turmaDAO = new TurmaDAO(ref _db);
                _turmaDAO.Insert(turma);
                this.Success(string.Format("Turma Cadastrada com sucesso."), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("ERRO ao Incluir cadastro! Tente novamente."));
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().OrderBy(x => x.CursoNome.ToUpper()), "idcurso", "cursonome");
            ViewBag.funcionario_idfuncionario = new SelectList(_funcionarioDAO.All().OrderBy(x => x.NomeCompleto.ToUpper()), "idfuncionario", "nomecompleto"); 
            return View("~/Views/Sistema/Turma/Create.cshtml", turma);
        }

        //
        // GET: /Turma/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VerificarSessao();

            TurmaDAO _turmasDAO = new TurmaDAO(ref _db);
            Turma _turma = new Turma();
            _turma = _turmasDAO.LoadById(id);

            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);

            if (_turma == null)
            {
                return HttpNotFound();
            }

            ViewBag.data_inicio = _turma.DataInicio;
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome.ToUpper()), "idcurso", "cursonome", _turma.Curso.IdCurso);
            ViewBag.funcionario_idfuncionario = new SelectList(_funcionarioDAO.All().OrderBy(x => x.NomeCompleto.ToUpper()).Where(x => x.Usuario.Perfil == "professor").ToList(), "idfuncionario", "nomecompleto", _turma.Funcionario.IdFuncionario);
            
            return View("~/Views/Sistema/Turma/Edit.cshtml", _turma);
        }

        //
        // POST: /Turma/Edit/5

        [HttpPost]
        public ActionResult Edit(Turma turma)
        {
            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);

            TurmaDAO _turmasDAO = new TurmaDAO(ref _db);
            Turma _turma = new Turma();

            if (ModelState.IsValid)
            {
                _turmasDAO.Update(turma);
                this.Success(string.Format("Turma Alterada com sucesso."), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("ERRO Turma não cadastrada! Tente novamente."));
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList().OrderBy(x => x.CursoNome.ToUpper()), "idcurso", "cursonome", _turma.Curso.IdCurso);
            ViewBag.funcionario_idfuncionario = new SelectList(_funcionarioDAO.All().ToList().OrderBy(x => x.NomeCompleto.ToUpper()), "idfuncionario", "nomecompleto", _turma.Funcionario.IdFuncionario);
            
            return View("~/Views/Sistema/Turma/Edit.cshtml", turma);
        }

        public ActionResult Delete(int id = 0)
        {
            TurmaDAO _turmaDAO = new TurmaDAO(ref _db);
            Turma _turma = new Turma();

            _turma = _turmaDAO.LoadById(id);

            CursoDAO _cursoDAO = new CursoDAO(ref _db);

            FuncionarioDAO _funcionarioDAO = new FuncionarioDAO(ref _db);

            if (_turma !=null)
            {
                _turmaDAO.Delete(_turma);

                this.Success(string.Format("Turma EXCLUÍDA com sucesso."), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("ERRO ao EXCLUIR Turma! Tente novamente."));
            ViewBag.curso_idcurso = new SelectList(_cursoDAO.All().ToList(), "idcurso", "cursonome", _turma.Curso.IdCurso);

SDE-FIC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDE_FIC.DAO;
using SDE_FIC.Models;
using PagedList;
using SDE_FIC.Util;

namespace SDE_FIC.Controllers
    
{
   
    public class UsuarioController : Controller
     
    {
        private DBConnect _db = new DBConnect();

        public ViewResult VerificarSessao()
        {
            if (Session["LogedUserNomeCompleto"] == null)
            {
                ViewBag.msg_Error = "Tempo de Sessão Expirou! Autentique novamente.";
                this.Danger(string.Format("Tempo de Sessão Expirou! Autentique novamente."));
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                var NomeComleto = Session["LogedUserNomeCompleto"].ToString();
            }
            return View();
        }
   
        //
        // GET: /Usuario/

        public ActionResult Index(int? pagina, string strCriterio)
        {
            VerificarSessao();

            int tamanhoPagina = 15;
            int numeroPagina = pagina ?? 1;

            CursoDAO _cursoDAO = new CursoDAO(ref _db);
            UsuarioDAO usuarioDAO = new UsuarioDAO(ref _db);

            List<Usuario> lUsuario = new List<Usuario>();
            

            if (strCriterio == null)
            {
                lUsuario = usuarioDAO.All().OrderBy(x => x.NomeCompleto).ToList();
            }
            else
            {
                lUsuario = usuarioDAO.All().OrderBy(x => x.NomeCompleto).Where(x => x.NomeCompleto.ToUpper().Contains(strCriterio.ToUpper())).ToList();
            }


            return View("~/Views/Sistema/Usuario/Index.cshtml", lUsuario.ToPagedList(numeroPagina, tamanhoPagina));
        }

        //
        // GET: /Usuario/Details/5

        public ActionResult Details(int id = 0)
        {
            VerificarSessao();

            UsuarioDAO usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = new Usuario();
            _usuario = usuarioDAO.LoadById(id);

            return View("~/Views/Sistema/Usuario/Details.cshtml", _usuario);
        }

        //
        // GET: /Usuario/Create

        public ActionResult Create()
        {
            VerificarSessao();

            return View("~/Views/Sistema/Usuario/Create.cshtml");
        }


        //
        // POST: /Usuario/Create

        [HttpPost]
        public ActionResult Create(Usuario usuario, int? pagina)
        {

            if (ModelState.IsValid)
            {
                UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
                _usuarioDAO.Insert(usuario);

                this.Success(string.Format("Registro salvo com sucesso!"),
                                                            true);
                return RedirectToAction("Index");
            }
            else
            {                
                this.Danger(string.Format("Falha ao Cadastrar Registro! Verifique se os campos estão preenchidos."));
            }
            return View("~/Views/Sistema/Usuario/Create.cshtml", usuario);
        }

        //
        // GET: /Usuario/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VerificarSessao();

            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = new Usuario();

            _usuario = _usuarioDAO.LoadById(id);

            if (_usuario == null)
            {
                return HttpNotFound();
            }
            return View("~/Views/Sistema/Usuario/Edit.cshtml", _usuario);
        }

        //
        // POST: /Usuario/Edit/5

        [HttpPost]
        public ActionResult Edit(Usuario usuario, int? pagina)
        {
            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario _usuario = _usuarioDAO.LoadById(usuario.IdUsuario);

            if (ModelState.IsValid)
            {

                _usuarioDAO.Update(usuario);
                this.Success(string.Format("Registro alterado com sucesso!"),
                                                            true);
                return RedirectToAction("Index");
            }
            else
            {
                this.Danger(string.Format("Falha ao Alterar Registro! Verifique se os campos estão preenchidos."));
            }
            return View("~/Views/Sistema/Usuario/Edit.cshtml", usuario);



        }

        //
        // POST: /Usuario/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UsuarioDAO _usuarioDAO = new UsuarioDAO(ref _db);
            Usuario usuario = new Usuario();
            usuario = _usuarioDAO.LoadById(id);

            if (usuario != null)
            {
                _usuarioDAO.Delete(usuario);
                this.Success(string.Format("Registro Excluído com sucesso!"), true);
                return RedirectToAction("Index");
            }
            this.Danger(string.Format("Registro NÃO Excluído, tente novamente!"), true);
            return RedirectToAction("Index");
        }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }
        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }
        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

SDE-FIC/Views/Sistema/Index-old.cshtml
@{
    ViewBag.Title = Session["LogedUserPerfil"];
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}

<div style="text-align:center;">
    <legend>
        <table style="width: 100%;">
            <tr><td>
                <h3 style="text-align:left;">Área do @Session["LogedUserPerfil"].ToString()</h3>
                <h5 style="text-align: left;">@ViewBag.Saudacao - @ViewBag.Data</h5></td>
                <td>                              
                </td>
                <td style="vertical-align: bottom; text-align:right">
                
                </td>

            </tr></table></legend>
    

</div>
<div style="height:100%;">
@*    <div style="width: 200px; height: 200px; background-color: lightyellow; float: left; border: 1px solid gray; padding: 5px; margin: 15px;">
        <b>Avisos</b><br /><hr />
        Entrega de lista de material didático deve ser realizada por email até o dia 01/03/2015
    </div>
    <div style="width: 200px; height: 200px; background-color: lightyellow; float: left; border: 1px solid gray; padding: 5px; margin: 15px;">
        <b>Reuniao</b><br /><hr />
        Em 07/02 haverá reunião com todos os professores do FIC.
        A participação é obrigatória para compensação de horas.
    </div>*@
    <div style="width: 100%; background-color: #b3efda; border: 1px solid gray; padding: 5px; margin: 0px; border-radius: 3px;">
        <b>Informações Úteis</b><br>
        <b>Cadastro de Novos Usuários, Alunos, Cursos, Unidades Curriculares, Evasão ou Transferência</b><br>
        <p style="text-align:justify;">
            Será realizado pela secretária.<br />
            Atualmente as pessoas responsáveis são: <br />Rodolfo (rodolfo.bazzuco@sp.senai.br) e Acácio (acacio.neto@sp.senai.br). <br />
            <br />
        <b>Cadastro de Frequência, Lançamento de Notas e Impressão de Fechamento</b><br>
        <p style="text-align:justify;">
            São realizados por cada docente que possui acesso ao sistema;<br />
            Preferencialmente as frequencias devem ser lançados no dia da aula;
            <br />
            <br />
        <b>Lançamento de Notas</b><br>
        <p style="text-align:justify;">
            As notas devem ser informadas de 0 a 100 (números inteiros) e
            somente as médias por módulo. 
            <br />
            Não adicionar mais de uma nota por módulo, pois a segunda nota não entra na média.
            A média se atualiza de acordo com o lançamento das notas.
            <br />
            <br />
        
        <b>Novas Funções/Correções</b><br>
        <p style="text-align:justify;">
            > 11/12/2017 - Implementado cadastro de aproveitamentos no diário da turma;
            <br />
            > 11/12/2017 - Implementado o cadastro da Sigla da Unidade Curricular, alterado tempo de seção para 60 min.;
            <br />
            > 04/12/2017 - Permitir o usuário Coordenador realize lançamentos/correções nos diários; Sugestão: Coord. Júlio Cesar
            <br />
            > 04/10/2017 - Conteudo organizado por data mais recente; Sugestão: Prof. Regiano
            <br />
            > 04/10/2017 - Realizado inclusão de função de Transferência;
            <br />
            > 09/10/2017 - Realizado inclusão de estatus de AP (Aproveitamento de Estudos) no lançamento da Frequência;
            <br /> 
            > 11/10/2017 - Corrígido Impressão de Relatório: data de conteúdo diferente de data de frequencia; Sugestão: Prof. Luciano
            <br />
            
    </div>
    
@*    <div style="width: 60%; background-color: #f5ffa6; float: left; border: 1px solid gray; padding: 5px; margin-left: 5px; margin-top: 5px; border-radius: 3px;">
        <b>Calendário de Turmas 2015</b><br>
        <p style="text-align:justify;">
            Para fazer o donwload do Calendário 2015 
            
            @Html.ActionLink("Clique Aqui","BaixarCalendario2015")
            <br />
            Encontre seu curso na guia.</p>   
    </div>*@

    <div style="width: 100% ;background-color: #d0f89c; border: 1px solid gray; padding: 5px; margin: 0px; border-radius: 3px;">
        <b>Aviso</b><br>
        <p style="text-align:justify;">Em 02/07/2015 foi implementado a utilização do SDE - Sistema de Diário Escolar, com o objetivo de realizar o controle academico
        de frequencia e notas dos alunos do FIC. <br />
        O sistema está passando por melhorias constantes. Caso encontre algum erro, dúvida ou sugestão, clique em
        @Html.ActionLink("Sugestões", "Index", "Sugestoes").
        </p>
       
    </div>
        <div style="clear: both;"></div>
</div>

SDE-FIC/Views/Sistema/Index.cshtml
@{
    ViewBag.Title = " Painel de Controle" + " | " +  Session["LogedUserPerfil"];
    Layout = "~/Views/Shared/_Layout_Sistema.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row">
        <div class="col-12">
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> Painel de Controle</li>
            </ol>
        </div>
    </div>
   
    <!--
    
        -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">

    <div class="col-sm-3">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@ViewBag.Turma</h3>

                <p>Turmas Cadastradas</p>
            </div>
            <div class="icon">
                <i class="ion ion-gear-b"></i>
            </div>
            <a href="@Url.Action("Index", "Turma", new { strCriterioStatus = 2 })" class="small-box-footer">Ver todos <i class="fa fa-arRows-circle-right"></i></a>
        </div>
    </div>

    <div class="col-sm-3">

        <div class="small-box bg-green">
            <div class="inner">
                <h3>@ViewBag.Usuario</h3>

                <p>Usuários Cadastrados</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            @if (Session["LogedUserPerfil"].ToString() != "professor")
            {
                <a href="@Url.Action("Index", "Usuario")" class="small-box-footer">Ver todos <i class="fa fa-arRows-circle-right"></i></a>
            }
            else
            {
                <a href="#" class="small-box-footer">&nbsp;Usuários Cadastrados</a>
            }

        </div>
    </div>

    <div class="col-sm-3">

        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>@ViewBag.DiariosAtivo</h3>

                <p>Diários Ativos</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="@Url.Action("Index", "Diario", new {strCriterioStatus = 1})" class="small-box-footer">Ver Todos <i class="fa fa-arRows-circle-right"></i></a>
        </div>
    </div>

    <div class="col-sm-3">

            <div class="small-box bg-red">
                <div class="inner">
                    <h3>@ViewBag.DiariosFinalizado</h3>

                    <p>Diários Finalizados</p>
                </div>
                <div class="icon">
                    <i class="ion ion-alert-circled"></i>
                </div>
                <a href="@Url.Action("Index", "Diario", new {strCriterioStatus = 0})" class="small-box-footer">Ver Todos <i class="fa fa-arRows-circle-right"></i></a>
            </div>
        </div>
     

    </div>

    <div class="row">
        <div class="col-sm-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>

              <h3 class="box-title">Informações</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="tab-pane active" id="tab_1-1">
                <b>Novas Funções</b>

                <p style="text-align:justify;">
                    <ul>
                        <li>30/11/2021 - Implementado método de inserção de presença individual na tela de listagem de frequencias;</li>

                        <li>30/11/2021 - Correção do método de troca de senha do usuário de perfil professor;</li>

                        <li>30/11/2021 - Permitido a edição de lançamento para alunos em status de Evadido (E);</li>

                        <li>11/06/2020 - Novo Layout Responsivo, que permite melhor uso com dispositivos Tablet e Mobile;</li>

                        <li>20/07/2018 - Implementado Função de Filtro de Turmas Ativas e Concluídas;</li>

                        <li>20/07/2018 - Implementado Função de Fechamento de Turma (Somente a Secretaria poderá Fechar e Reabrir a Turma);</li>

                        <li>20/07/2018 - Implementado Importação de Alunos para Turma;</li>

                        <li>20/07/2018 - Implementado Tipo de Lançamento de Reposição no diário "R";</li>

                        <li>20/07/2018 - Implementado Lançamento Individual de Frequência;</li>

                        <li>11/12/2017 - Implementado cadastro de aproveitamentos no diário da turma;</li>

                        <li>11/12/2017 - Implementado o cadastro da Sigla da Unidade Curricular, alterado tempo de seção para 60 min.;</li>

                        <li>04/12/2017 - Permitir o usuário Coordenador realize lançamentos/correções nos diários; Sugestão: Coord. Júlio Cesar</li>

                        <li>04/10/2017 - Conteudo organizado por data mais recente; Sugestão: Prof. Regiano</li>

                        <li>04/10/2017 - Realizado inclusão de função de Transferência;</li>

                        <li>09/10/2017 - Realizado inclusão de estatus de AP (Aproveitamento de Estudos) no lançamento da Frequência;</li>

                        <li>11/10/2017 - Corrígido Impressão de Relatório: data de conteúdo diferente de data de frequencia; Sugestão: Prof. Luciano</li>

                    </ul>
                </p>
                  
                <b>Informações Úteis</b>
                  <ul>
                    <li>Cadastro de Novos Usuários, Alunos, Cursos, Unidades Curriculares, Evasão ou Transferência, são realizados pela secretária.
                    Atualmente as pessoas responsáveis são: <br />Rodolfo (rodolfo.bazzuco@sp.senai.br) e Daiane (asact792@sp.senai.br).
                    </li>
                    <li>Cadastro de Frequência, Lançamento de Notas e Impressão de Fechamento, são realizados por cada docente que possui acesso ao sistema;
                    Preferencialmente as frequencias devem ser lançados no dia da aula;
                    </li>
                    <li>Lançamento de Notas
                    As notas devem ser informadas de 0 a 100 (números inteiros) e
                    somente as médias por módulo. 
                    Não adicionar mais de uma nota por módulo, pois a segunda nota não entra na média.
                    A média se atualiza de acordo com o lançamento das notas.
                    </li>

                    </ul>

              </div>

            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>

    </div>

</section>

<!-- /.content -->
<!--FIM Conteudo-->

SDE-FIC/Views/Sistema/_Mensagem_Error.cshtml
<!-- Modal Mensagem-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">@ViewBag.Title</h4>
      </div>
      <div class="modal-body">
          <div class="alert alert-error">
        @TempData["Mensagem"]
          </div>
@*      </div>
      <div class="modal-footer">*@
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
@*        <button type="button" class="btn btn-primary">Save changes</button>*@
      </div>
    </div>
  </div>
</div>

SDE-FIC/Views/Sistema/_Mensagem_Success.cshtml
<!-- Modal Mensagem-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">@ViewBag.Title</h4>
      </div>
      <div class="modal-body">
          <div class="alert alert-success">
        @TempData["Mensagem"]
          </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>